package com.ja.xmlgeneratorspring.entity;
// Generated 2017-04-16 17:46:31 by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * Bany generated by hbm2java
 */
@Entity
@Table(name = "bany")
public class Ban  implements java.io.Serializable {

    @Id
    @GeneratedValue
     private Integer idBan;
     private String ip;

    public Ban() {
    }

    public Ban(String ip) {
       this.ip = ip;
    }
   
    public Integer getIdBan() {
        return this.idBan;
    }
    
    public void setIdBan(Integer idBan) {
        this.idBan = idBan;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }




}


