package com.ja.xmlgeneratorspring.entity;
// Generated 2017-04-16 17:46:31 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Logi generated by hbm2java
 */
@Entity
@Table(name = "logi")
public class Log  implements java.io.Serializable {

    @Id
    @GeneratedValue
     private Integer idLog;
     private Date czas;
     private String ip;
     private Boolean czyWykonane;

    public Log() {
    }

    public Log(Date czas, String ip, Boolean czyWykonane) {
       this.czas = czas;
       this.ip = ip;
       this.czyWykonane = czyWykonane;
    }
   
    public Integer getIdLog() {
        return this.idLog;
    }
    
    public void setIdLog(Integer idLog) {
        this.idLog = idLog;
    }
    public Date getCzas() {
        return this.czas;
    }
    
    public void setCzas(Date czas) {
        this.czas = czas;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public Boolean getCzyWykonane() {
        return this.czyWykonane;
    }
    
    public void setCzyWykonane(Boolean czyWykonane) {
        this.czyWykonane = czyWykonane;
    }




}


